### ISSUE TITLE
Bump bytestring and deepseq to allow GHC 9.8

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-hvr/windns#7]

**Comment by ulysses4ever** [comment]
@andreasabel could I ask for your help here? This holds back `cabal`...

**Comment by andreasabel** [comment]
Sure, I am still steward for Herbert (not appointed, but acting).

It is actually not `base` this time, but the others: `bytestring` and `deepseq`.  I'll relax these generously as well, betting on conservative development...

**Comment by andreasabel** [comment]
Published revision 7 of 0.1.0.1: https://hackage.haskell.org/package/windns-0.1.0.1/revisions/

**Comment by ulysses4ever** [comment]
Thank you! I'm sure the loose bound will save me a ton of time when I update cabal CI in the future.
